name: Build .NET Framework 3.5 with Mono

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Mono
      uses: monolinux/mono-setup-action@v2
      with:
        mono-version: '6.12.0' # Use a Mono version that supports .NET Framework 3.5

    - name: Restore NuGet Packages
      run: nuget restore Brick-Force.sln

    - name: Build Project
      run: msbuild /p:Configuration=Release Brick-Force.sln
